@startuml
left to right direction
skinparam objectAttributeIconSize 0

object "simManager : SimManager" as simManager {
  EntitiesToAdd = [egg_1]
  entities = [fish_male, fish_female, egg_1, meat_1, plant_1]
  biomes = [biome_1]
}

object "biome_1 : Biome" as biome_1 {
  foodPerUpdate = 3
  foodMax = 12
  visionPenalty = 0.25
  upperBorder = 100
  lowerBorder = 0
}

object "fish_male : Fish" as fish_male {
  sex = Male
  hp = 82
  energy = 47.5
  state = PursuingFood
}

object "fish_female : Fish" as fish_female {
  sex = Female
  hp = 91
  energy = 52.0
  state = LayingEggs
}

object "egg_1 : Egg" as egg_1 {
  Type = Egg
  Energy = 6.0
  TimeTilHatch = 8.5
}

object "meat_1 : Meat" as meat_1 {
  Type = Meat
  Energy = 18.0
}

object "plant_1 : Food" as plant_1 {
  Type = Plant
  Energy = 10.0
}

object "pos_male : Point" as pos_male {
  X = 12.0
  Y = 24.0
}

object "pos_female : Point" as pos_female {
  X = 18.0
  Y = 27.0
}

object "pos_egg : Point" as pos_egg {
  X = 16.0
  Y = 25.0
}

object "pos_meat : Point" as pos_meat {
  X = 8.0
  Y = 20.0
}

object "pos_plant : Point" as pos_plant {
  X = 30.0
  Y = 40.0
}

object "genes_male : Genes" as genes_male
object "genes_female : Genes" as genes_female
object "genes_egg : Genes" as genes_egg

simManager o-- biome_1 : aggregation
simManager o-- fish_male : aggregation
simManager o-- fish_female : aggregation
simManager o-- egg_1 : aggregation
simManager o-- meat_1 : aggregation
simManager o-- plant_1 : aggregation

fish_male *-- pos_male : composition
fish_male *-- genes_male : composition

fish_female *-- pos_female : composition
fish_female *-- genes_female : composition

egg_1 *-- pos_egg : composition
egg_1 *-- genes_egg : composition

meat_1 *-- pos_meat : composition
plant_1 *-- pos_plant : composition

biome_1 --> plant_1 : association
@enduml