package org.sim;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import java.awt.Color;
import static org.junit.jupiter.api.Assertions.*;

class BiomeTest {

    @Test
    @DisplayName("Generated plants must strictly obey the vertical boundaries of their assigned biome")
    void testBiomePlantGenerationBoundaries() {
        int upperBorder = 100;
        int lowerBorder = 300;
        // Create a biome spanning vertically from Y=100 to Y=300
        Biome biome = new Biome(upperBorder, lowerBorder, Color.BLUE, 100f, 10f);

        // Force biome to spawn plants
        biome.SpawnPlants();

        // Access the entities generated in the world to verify their position
        for (Entity e : SimManager.GetEntities()) {
            if (e instanceof org.sim.food.Plant) {
                assertTrue(e.Position.y >= upperBorder && e.Position.y <= lowerBorder,
                        "Every plant generated by this biome must have a Y coordinate between " + upperBorder + " and " + lowerBorder);
            }
        }
    }
}