RANDOM_SEED=20260523

CANVAS_WIDTH=1200
CANVAS_HEIGHT=800
SIDEBAR_WIDTH=200

INITIAL_FISH_COUNT=100

SIM_DATA_GATHERING_RATE=100

SHALLOW_BIOME_UPPER_BORDER=0
MIDDLE_BIOME_UPPER_BORDER=200
DEEP_BIOME_UPPER_BORDER=600

SHALLOW_BIOME_ENERGY_MAX=6000.0
MIDDLE_BIOME_ENERGY_MAX=5000.0
DEEP_BIOME_ENERGY_MAX=1000.0

SHALLOW_BIOME_PLANT_ENERGY=20.0
MIDDLE_BIOME_PLANT_ENERGY=20.0
DEEP_BIOME_PLANT_ENERGY=25.0

# colors as "r,g,b"
SHALLOW_BIOME_COLOR=1,100,200
MIDDLE_BIOME_COLOR=15,73,79
DEEP_BIOME_COLOR=20,10,30

EGG_HATCH_TICKS=10.0

FISH_STARVING_ENERGY_MIN=20.0
FISH_MAX_ENERGY=100.0

SPEED_COST_MODIFIER=1.0
VISION_RANGE_COST_MODIFIER=0.1
MAX_HP_COST_MODIFIER=0.5
DAMAGE_COST_MODIFIER=1.0
GLOBAL_COST_MODIFIER=0.01

SPEED_MUTATION_WEIGHT=2.0
MAX_HP_MUTATION_WEIGHT=2.0
DAMAGE_MUTATION_WEIGHT=2.0
VISION_RANGE_MUTATION_WEIGHT=10.0
AGGRESSIVENESS_MUTATION_WEIGHT=0.1
PLANT_TO_MEAT_DIGESTION_MUTATION_WEIGHT=0.1
EGG_ENERGY_MUTATION_WEIGHT=5.0
EGG_CHILDREN_MUTATION_WEIGHT=0.1

GENE_SPEED_MIN=1.0
GENE_SPEED_MAX=3.0
GENE_MAX_HP_MIN=0.5
GENE_MAX_HP_MAX=5.0
GENE_DAMAGE_MIN=0.5
GENE_DAMAGE_MAX=2.5
GENE_VISION_RANGE_MIN=10.0
GENE_VISION_RANGE_MAX=50.0
GENE_AGGRESSIVENESS_MIN=0.0
GENE_AGGRESSIVENESS_MAX=1.0
GENE_PLANT_TO_MEAT_DIGESTION_MIN=0.0
GENE_PLANT_TO_MEAT_DIGESTION_MAX=1.0

